wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.948731144599374
max_depth:
  desc: null
  value: 15
min_child_weight:
  desc: null
  value: 0.06395314328906762
n_estimators:
  desc: null
  value: 376
num_leaves:
  desc: null
  value: 34
reg_alpha:
  desc: null
  value: 1.365198974137595
reg_lambda:
  desc: null
  value: 1.0278283706473381
subsample:
  desc: null
  value: 0.7084238113438425
