wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9840596970579132
max_depth:
  desc: null
  value: 99
min_child_weight:
  desc: null
  value: 0.018873330347262154
n_estimators:
  desc: null
  value: 1516
num_leaves:
  desc: null
  value: 317
reg_alpha:
  desc: null
  value: 1.38699586338711
reg_lambda:
  desc: null
  value: 1.4463118586793655
subsample:
  desc: null
  value: 0.5855216949098908
