wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.4625934627465564
max_depth:
  desc: null
  value: 11
min_child_weight:
  desc: null
  value: 0.06894681747801458
n_estimators:
  desc: null
  value: 1417
num_leaves:
  desc: null
  value: 383
reg_alpha:
  desc: null
  value: 1.4166616510683079
reg_lambda:
  desc: null
  value: 1.484429528400756
subsample:
  desc: null
  value: 0.6050804008006565
