wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.16190222280203967
max_depth:
  desc: null
  value: 39
min_child_weight:
  desc: null
  value: 0.021670630248785263
n_estimators:
  desc: null
  value: 1248
num_leaves:
  desc: null
  value: 180
reg_alpha:
  desc: null
  value: 1.2922665395460629
reg_lambda:
  desc: null
  value: 1.2480863322602471
subsample:
  desc: null
  value: 0.9768474264923966
