wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9849725836743197
max_depth:
  desc: null
  value: 77
min_child_weight:
  desc: null
  value: 0.054161426306884045
n_estimators:
  desc: null
  value: 4562
num_leaves:
  desc: null
  value: 25
reg_alpha:
  desc: null
  value: 1.0142757025668174
reg_lambda:
  desc: null
  value: 1.0143201668470159
subsample:
  desc: null
  value: 0.8807645839353218
