wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.11775018957909439
max_depth:
  desc: null
  value: 38
min_child_weight:
  desc: null
  value: 0.07355881208539519
n_estimators:
  desc: null
  value: 2352
num_leaves:
  desc: null
  value: 492
reg_alpha:
  desc: null
  value: 1.2613105209485187
reg_lambda:
  desc: null
  value: 1.2164956183959685
subsample:
  desc: null
  value: 0.7637763998170274
