wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.8994301358130806
max_depth:
  desc: null
  value: 96
min_child_weight:
  desc: null
  value: 0.08259584700446332
n_estimators:
  desc: null
  value: 383
num_leaves:
  desc: null
  value: 424
reg_alpha:
  desc: null
  value: 1.4415608645532736
reg_lambda:
  desc: null
  value: 1.1214303702466353
subsample:
  desc: null
  value: 0.9258988464358583
