wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.987906098964942
max_depth:
  desc: null
  value: 50
min_child_weight:
  desc: null
  value: 0.06251520275439774
n_estimators:
  desc: null
  value: 2536
num_leaves:
  desc: null
  value: 11
reg_alpha:
  desc: null
  value: 1.0842872363196248
reg_lambda:
  desc: null
  value: 1.1289751877224277
subsample:
  desc: null
  value: 0.9788609978989933
