wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.20530759202504353
max_depth:
  desc: null
  value: 38
min_child_weight:
  desc: null
  value: 0.043525916459797066
n_estimators:
  desc: null
  value: 4525
num_leaves:
  desc: null
  value: 186
reg_alpha:
  desc: null
  value: 1.283548440684156
reg_lambda:
  desc: null
  value: 1.2841071207061576
subsample:
  desc: null
  value: 0.20994268500590338
