wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.6682862404224276
max_depth:
  desc: null
  value: 27
min_child_weight:
  desc: null
  value: 0.03255539418871873
n_estimators:
  desc: null
  value: 2058
num_leaves:
  desc: null
  value: 391
reg_alpha:
  desc: null
  value: 1.3451577605204705
reg_lambda:
  desc: null
  value: 1.1046702270032953
subsample:
  desc: null
  value: 0.6082584150410459
