wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9819993438503271
max_depth:
  desc: null
  value: 100
min_child_weight:
  desc: null
  value: 0.08726562215287312
n_estimators:
  desc: null
  value: 3480
num_leaves:
  desc: null
  value: 346
reg_alpha:
  desc: null
  value: 1.0695652083636125
reg_lambda:
  desc: null
  value: 1.453205002441712
subsample:
  desc: null
  value: 0.8518493072922988
