wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.08587041321748674
max_depth:
  desc: null
  value: 61
min_child_weight:
  desc: null
  value: 0.0035654137621016465
n_estimators:
  desc: null
  value: 4786
num_leaves:
  desc: null
  value: 430
reg_alpha:
  desc: null
  value: 1.1418732364021993
reg_lambda:
  desc: null
  value: 1.4363239933561323
subsample:
  desc: null
  value: 0.8480627541167557
