wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.25747247329758105
max_depth:
  desc: null
  value: 17
min_child_weight:
  desc: null
  value: 0.03867335944037433
n_estimators:
  desc: null
  value: 3858
num_leaves:
  desc: null
  value: 380
reg_alpha:
  desc: null
  value: 1.133995365080533
reg_lambda:
  desc: null
  value: 1.2074678112752635
subsample:
  desc: null
  value: 0.7507536163905387
