wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.6300326423714233
max_depth:
  desc: null
  value: 86
min_child_weight:
  desc: null
  value: 0.07402068603514285
n_estimators:
  desc: null
  value: 3578
num_leaves:
  desc: null
  value: 355
reg_alpha:
  desc: null
  value: 1.077658639119499
reg_lambda:
  desc: null
  value: 1.1690378698983446
subsample:
  desc: null
  value: 0.5263209603184117
