wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9340590003651421
max_depth:
  desc: null
  value: 52
min_child_weight:
  desc: null
  value: 0.06362536624382031
n_estimators:
  desc: null
  value: 4875
num_leaves:
  desc: null
  value: 445
reg_alpha:
  desc: null
  value: 1.0463324527884041
reg_lambda:
  desc: null
  value: 1.0781802927751019
subsample:
  desc: null
  value: 0.9800289788069461
