wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.8985945071367631
max_depth:
  desc: null
  value: 91
min_child_weight:
  desc: null
  value: 0.015958913641026688
n_estimators:
  desc: null
  value: 2826
num_leaves:
  desc: null
  value: 373
reg_alpha:
  desc: null
  value: 1.3841464598197226
reg_lambda:
  desc: null
  value: 1.0080198909721214
subsample:
  desc: null
  value: 0.8229321568188643
