wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.97588288244323
max_depth:
  desc: null
  value: 97
min_child_weight:
  desc: null
  value: 0.09128588396843001
n_estimators:
  desc: null
  value: 4169
num_leaves:
  desc: null
  value: 159
reg_alpha:
  desc: null
  value: 1.3012975347988254
reg_lambda:
  desc: null
  value: 1.4835994290264785
subsample:
  desc: null
  value: 0.8322790324550907
