wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.7719274592356546
max_depth:
  desc: null
  value: 45
min_child_weight:
  desc: null
  value: 0.02466154416667933
n_estimators:
  desc: null
  value: 2956
num_leaves:
  desc: null
  value: 204
reg_alpha:
  desc: null
  value: 1.3457051205744672
reg_lambda:
  desc: null
  value: 1.0325186278591054
subsample:
  desc: null
  value: 0.8896812093848864
