wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.976264386773718
max_depth:
  desc: null
  value: 28
min_child_weight:
  desc: null
  value: 0.012863453542526836
n_estimators:
  desc: null
  value: 2088
num_leaves:
  desc: null
  value: 169
reg_alpha:
  desc: null
  value: 1.1761872877864163
reg_lambda:
  desc: null
  value: 1.0016050594374721
subsample:
  desc: null
  value: 0.7058752940901286
