wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.8373236062903836
max_depth:
  desc: null
  value: 48
min_child_weight:
  desc: null
  value: 0.018588407578402015
n_estimators:
  desc: null
  value: 3029
num_leaves:
  desc: null
  value: 373
reg_alpha:
  desc: null
  value: 1.2894345944123045
reg_lambda:
  desc: null
  value: 1.0612952981567263
subsample:
  desc: null
  value: 0.6748225933855581
