wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9989031602589383
max_depth:
  desc: null
  value: 9
min_child_weight:
  desc: null
  value: 0.07126890722426045
n_estimators:
  desc: null
  value: 1213
num_leaves:
  desc: null
  value: 344
reg_alpha:
  desc: null
  value: 1.0521882336732706
reg_lambda:
  desc: null
  value: 1.3069928421821844
subsample:
  desc: null
  value: 0.388656130202655
