wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.8524868382542324
max_depth:
  desc: null
  value: 99
min_child_weight:
  desc: null
  value: 0.09868149282988257
n_estimators:
  desc: null
  value: 4884
num_leaves:
  desc: null
  value: 245
reg_alpha:
  desc: null
  value: 1.432154716197643
reg_lambda:
  desc: null
  value: 1.4096235930550065
subsample:
  desc: null
  value: 0.9303309768850415
