wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.8842058977315286
max_depth:
  desc: null
  value: 65
min_child_weight:
  desc: null
  value: 0.003307984952340568
n_estimators:
  desc: null
  value: 1840
num_leaves:
  desc: null
  value: 448
reg_alpha:
  desc: null
  value: 1.1562838305971186
reg_lambda:
  desc: null
  value: 1.047843788256576
subsample:
  desc: null
  value: 0.9681882495445094
