wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9173392250959264
max_depth:
  desc: null
  value: 6
min_child_weight:
  desc: null
  value: 0.09846454006506174
n_estimators:
  desc: null
  value: 4564
num_leaves:
  desc: null
  value: 435
reg_alpha:
  desc: null
  value: 1.1348587593871253
reg_lambda:
  desc: null
  value: 1.0464571986724345
subsample:
  desc: null
  value: 0.8702616479871366
