wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.45615018363315196
max_depth:
  desc: null
  value: 29
min_child_weight:
  desc: null
  value: 0.08314149769753508
n_estimators:
  desc: null
  value: 62
num_leaves:
  desc: null
  value: 125
reg_alpha:
  desc: null
  value: 1.3137616013305502
reg_lambda:
  desc: null
  value: 1.167560798261447
subsample:
  desc: null
  value: 0.1658424041540174
