wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9967806819781091
max_depth:
  desc: null
  value: 33
min_child_weight:
  desc: null
  value: 0.037984957998961615
n_estimators:
  desc: null
  value: 141
num_leaves:
  desc: null
  value: 332
reg_alpha:
  desc: null
  value: 1.0815316484061197
reg_lambda:
  desc: null
  value: 1.0120305850145068
subsample:
  desc: null
  value: 0.8732348945428877
