wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.5352085764520865
max_depth:
  desc: null
  value: 28
min_child_weight:
  desc: null
  value: 0.009928330038073509
n_estimators:
  desc: null
  value: 2520
num_leaves:
  desc: null
  value: 410
reg_alpha:
  desc: null
  value: 1.4461930248525623
reg_lambda:
  desc: null
  value: 1.1339645852261435
subsample:
  desc: null
  value: 0.5346960203994874
