wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9729291165791706
max_depth:
  desc: null
  value: 57
min_child_weight:
  desc: null
  value: 0.07025332473409938
n_estimators:
  desc: null
  value: 768
num_leaves:
  desc: null
  value: 73
reg_alpha:
  desc: null
  value: 1.47189353109996
reg_lambda:
  desc: null
  value: 1.0203666161269538
subsample:
  desc: null
  value: 0.590181237352301
