wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9946659354961653
max_depth:
  desc: null
  value: 39
min_child_weight:
  desc: null
  value: 0.05345831196783344
n_estimators:
  desc: null
  value: 3903
num_leaves:
  desc: null
  value: 173
reg_alpha:
  desc: null
  value: 1.472305739357087
reg_lambda:
  desc: null
  value: 1.1318863434844442
subsample:
  desc: null
  value: 0.08898411688920678
