wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.991641249080885
max_depth:
  desc: null
  value: 72
min_child_weight:
  desc: null
  value: 0.09441056118028175
n_estimators:
  desc: null
  value: 3397
num_leaves:
  desc: null
  value: 180
reg_alpha:
  desc: null
  value: 1.0774481857515963
reg_lambda:
  desc: null
  value: 1.3066789739216813
subsample:
  desc: null
  value: 0.9288166157604484
