wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9955493828499284
max_depth:
  desc: null
  value: 55
min_child_weight:
  desc: null
  value: 0.04796623480122003
n_estimators:
  desc: null
  value: 2475
num_leaves:
  desc: null
  value: 187
reg_alpha:
  desc: null
  value: 1.073174954513542
reg_lambda:
  desc: null
  value: 1.0452284510855891
subsample:
  desc: null
  value: 0.19845146815399148
