wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.869646594991507
max_depth:
  desc: null
  value: 27
min_child_weight:
  desc: null
  value: 0.04790673016901657
n_estimators:
  desc: null
  value: 3985
num_leaves:
  desc: null
  value: 305
reg_alpha:
  desc: null
  value: 1.2699147408612055
reg_lambda:
  desc: null
  value: 1.1426534177173986
subsample:
  desc: null
  value: 0.35869918858149163
