wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.7484710774346615
max_depth:
  desc: null
  value: 27
min_child_weight:
  desc: null
  value: 0.05995959529459558
n_estimators:
  desc: null
  value: 3325
num_leaves:
  desc: null
  value: 347
reg_alpha:
  desc: null
  value: 1.4515942270326812
reg_lambda:
  desc: null
  value: 1.117698842971689
subsample:
  desc: null
  value: 0.1988447379803359
