wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9889087334559042
max_depth:
  desc: null
  value: 6
min_child_weight:
  desc: null
  value: 0.055037139214937046
n_estimators:
  desc: null
  value: 4307
num_leaves:
  desc: null
  value: 218
reg_alpha:
  desc: null
  value: 1.288572619933967
reg_lambda:
  desc: null
  value: 1.0363613617663323
subsample:
  desc: null
  value: 0.8300084766591828
