wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.7114902497925818
max_depth:
  desc: null
  value: 63
min_child_weight:
  desc: null
  value: 0.03730775662776144
n_estimators:
  desc: null
  value: 4440
num_leaves:
  desc: null
  value: 144
reg_alpha:
  desc: null
  value: 1.3687328602044415
reg_lambda:
  desc: null
  value: 1.1518170233019853
subsample:
  desc: null
  value: 0.7732070383687237
