wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.7131285781106127
max_depth:
  desc: null
  value: 48
min_child_weight:
  desc: null
  value: 0.016554286817688637
n_estimators:
  desc: null
  value: 57
num_leaves:
  desc: null
  value: 495
reg_alpha:
  desc: null
  value: 1.127067121648678
reg_lambda:
  desc: null
  value: 1.0866660384396807
subsample:
  desc: null
  value: 0.8613663259993085
