wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.09381640422490793
max_depth:
  desc: null
  value: 94
min_child_weight:
  desc: null
  value: 0.05931879711990576
n_estimators:
  desc: null
  value: 282
num_leaves:
  desc: null
  value: 74
reg_alpha:
  desc: null
  value: 1.2312754906347554
reg_lambda:
  desc: null
  value: 1.4307867811911081
subsample:
  desc: null
  value: 0.4026409367245534
