wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9678940412317323
max_depth:
  desc: null
  value: 29
min_child_weight:
  desc: null
  value: 0.061299347311346515
n_estimators:
  desc: null
  value: 591
num_leaves:
  desc: null
  value: 27
reg_alpha:
  desc: null
  value: 1.4392192700185256
reg_lambda:
  desc: null
  value: 1.1134016083744995
subsample:
  desc: null
  value: 0.49961970688308577
