wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9673192598989964
max_depth:
  desc: null
  value: 5
min_child_weight:
  desc: null
  value: 0.050455705133205374
n_estimators:
  desc: null
  value: 4385
num_leaves:
  desc: null
  value: 304
reg_alpha:
  desc: null
  value: 1.3942310181190378
reg_lambda:
  desc: null
  value: 1.1047230235823295
subsample:
  desc: null
  value: 0.32938496117789545
