wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.5790833608840202
max_depth:
  desc: null
  value: 84
min_child_weight:
  desc: null
  value: 0.05206873916791259
n_estimators:
  desc: null
  value: 3832
num_leaves:
  desc: null
  value: 487
reg_alpha:
  desc: null
  value: 1.3147990981325437
reg_lambda:
  desc: null
  value: 1.2395915706373715
subsample:
  desc: null
  value: 0.679977388355534
