wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.02134697913255737
max_depth:
  desc: null
  value: 84
min_child_weight:
  desc: null
  value: 0.07763367576442395
n_estimators:
  desc: null
  value: 1915
num_leaves:
  desc: null
  value: 434
reg_alpha:
  desc: null
  value: 1.1462965414590214
reg_lambda:
  desc: null
  value: 1.4360616663938601
subsample:
  desc: null
  value: 0.5973405009809306
