wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    code_path: code/work/gp_learning_curves.py
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
