wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.9716598484648202
max_depth:
  desc: null
  value: 26
min_child_weight:
  desc: null
  value: 0.036112661351186494
n_estimators:
  desc: null
  value: 3999
num_leaves:
  desc: null
  value: 208
reg_alpha:
  desc: null
  value: 1.1446412128291061
reg_lambda:
  desc: null
  value: 1.1153357672918283
subsample:
  desc: null
  value: 0.12446237159972075
