wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.966108029312964
max_depth:
  desc: null
  value: 6
min_child_weight:
  desc: null
  value: 0.0606214229580703
n_estimators:
  desc: null
  value: 4777
num_leaves:
  desc: null
  value: 155
reg_alpha:
  desc: null
  value: 1.0045557143388
reg_lambda:
  desc: null
  value: 1.123094551273638
subsample:
  desc: null
  value: 0.9513537861645394
