wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
colsample_bytree:
  desc: null
  value: 0.8002733303880594
max_depth:
  desc: null
  value: 81
min_child_weight:
  desc: null
  value: 0.09890120757081812
n_estimators:
  desc: null
  value: 3373
num_leaves:
  desc: null
  value: 260
reg_alpha:
  desc: null
  value: 1.4845267825024124
reg_lambda:
  desc: null
  value: 1.4715508098030408
subsample:
  desc: null
  value: 0.371651719009638
